"""
Bundled sample articles for DEMO / offline use.

These are used by /api/articles ONLY when no NEWSDATA_API_KEY is configured
or the live NewsData.io request fails. When a real key is present the app
behaves exactly as before — this module is a graceful fallback so the UI can
be demoed end-to-end without any API keys.

Content is original placeholder text written for this demo (not scraped),
long enough to exercise the scoring/analysis flow.
"""

SAMPLE_ARTICLES = [
    {
        "id": "demo-001",
        "title": "Central bank holds interest rates steady as inflation continues to cool",
        "description": "Policymakers voted to keep the benchmark rate unchanged, citing steady progress on inflation while signalling caution about cutting too soon.",
        "content": (
            "The central bank's policy committee voted to hold its benchmark interest rate "
            "steady on Wednesday, pointing to a gradual cooling in inflation alongside a labour "
            "market that remains resilient. In its statement, the committee said recent data had "
            "increased its confidence that price growth is moving sustainably toward its two "
            "percent target, but stopped short of signalling imminent cuts. Officials emphasised "
            "that future decisions would depend on incoming data rather than a preset path. "
            "Economists broadly welcomed the measured tone, noting the bank appeared keen to "
            "avoid easing prematurely. Markets were little changed following the announcement."
        ),
        "source": "reuters", "source_name": "Reuters",
        "url": "https://example.com/demo-001",
        "image_url": "", "published_at": "2026-06-12 14:00:00",
        "category": ["business"], "country": ["united states of america"],
    },
    {
        "id": "demo-002",
        "title": "Large study links consistent sleep schedules to better long-term heart health",
        "description": "Researchers tracking more than 70,000 adults found that regular sleep and wake times were associated with a lower risk of cardiovascular events.",
        "content": (
            "A study following more than seventy thousand adults over several years has found "
            "that people with consistent sleep and wake times had a measurably lower risk of "
            "cardiovascular events than those whose schedules varied widely from night to night. "
            "The researchers, publishing in a peer-reviewed cardiology journal, controlled for "
            "factors including age, body mass index, exercise and existing health conditions. "
            "They cautioned that the work shows an association rather than proof of cause, and "
            "that further trials would be needed to confirm the mechanism. Independent experts "
            "described the findings as consistent with earlier research on circadian rhythms and "
            "urged readers not to over-interpret a single observational study."
        ),
        "source": "apnews", "source_name": "AP News",
        "url": "https://example.com/demo-002",
        "image_url": "", "published_at": "2026-06-11 09:30:00",
        "category": ["health"], "country": ["united states of america"],
    },
    {
        "id": "demo-003",
        "title": "Major technology firms announce new AI safety commitments at international summit",
        "description": "A group of leading developers pledged voluntary testing and disclosure measures, though critics questioned how the commitments would be enforced.",
        "content": (
            "Several of the world's largest technology companies used an international summit to "
            "announce a set of voluntary commitments on artificial intelligence safety, including "
            "independent testing of advanced models before release and clearer disclosure when "
            "content is generated by AI. Government representatives present described the pledges "
            "as a meaningful step, while a number of researchers and civil-society groups argued "
            "that voluntary measures without external enforcement risk amounting to little more "
            "than public relations. The companies said they would publish progress reports and "
            "work with regulators on shared standards. Analysts noted that similar pledges in the "
            "past had produced mixed results."
        ),
        "source": "theverge", "source_name": "The Verge",
        "url": "https://example.com/demo-003",
        "image_url": "", "published_at": "2026-06-10 17:45:00",
        "category": ["technology"], "country": ["united states of america"],
    },
    {
        "id": "demo-004",
        "title": "SHOCKING: This one common kitchen spice 'melts fat overnight', wellness influencers claim",
        "description": "Viral posts promise dramatic weight loss from a single ingredient, but dietitians say the claims are unsupported and potentially misleading.",
        "content": (
            "A wave of viral social-media posts is promising that a single common kitchen spice "
            "can 'melt fat overnight' and 'flush toxins' without any change to diet or exercise. "
            "The posts, many of them linking to a product for sale, feature dramatic before-and-"
            "after images and urge readers to 'act now before this is banned'. Registered "
            "dietitians contacted for comment said there is no credible evidence that any single "
            "spice produces rapid weight loss, and warned that the emotional, urgent language and "
            "lack of named sources are classic signs of a misleading health claim. They advised "
            "readers to be sceptical of anything promising effortless results and to consult a "
            "qualified professional before changing their diet."
        ),
        "source": "healthbuzz", "source_name": "HealthBuzz Daily",
        "url": "https://example.com/demo-004",
        "image_url": "", "published_at": "2026-06-12 08:15:00",
        "category": ["health"], "country": ["united states of america"],
    },
    {
        "id": "demo-005",
        "title": "Election officials report smooth voting as turnout climbs in regional races",
        "description": "Local authorities said polling ran largely without incident, pushing back on unverified online claims of widespread irregularities.",
        "content": (
            "Election officials across several regions reported a largely smooth voting process "
            "with higher-than-expected turnout, even as unverified claims of widespread "
            "irregularities circulated on social media. Officials said the isolated issues that "
            "did occur, such as a small number of delayed openings, were resolved quickly and "
            "documented through official channels. They urged voters to rely on verified results "
            "from local authorities rather than anonymous posts. Independent observers monitoring "
            "the process described it as orderly and transparent, and reminded the public that "
            "final tallies can take time to certify."
        ),
        "source": "apnews", "source_name": "AP News",
        "url": "https://example.com/demo-005",
        "image_url": "", "published_at": "2026-06-11 21:10:00",
        "category": ["politics"], "country": ["united states of america"],
    },
    {
        "id": "demo-006",
        "title": "Astronomers detect unusually bright signal from distant galaxy",
        "description": "A newly observed burst of energy has intrigued researchers, who stress that more data is needed before drawing conclusions.",
        "content": (
            "Astronomers have detected an unusually bright and brief burst of energy originating "
            "from a distant galaxy, adding to a growing catalogue of so-called fast radio bursts "
            "whose origins remain debated. The team behind the observation said the signal's "
            "characteristics were consistent with natural astrophysical processes, and cautioned "
            "against speculation about exotic explanations. They plan to coordinate with other "
            "observatories to gather follow-up data. Outside scientists praised the careful, "
            "measured presentation of the result, noting that extraordinary claims in astronomy "
            "require correspondingly strong and repeatable evidence."
        ),
        "source": "sciencedaily", "source_name": "Science Daily",
        "url": "https://example.com/demo-006",
        "image_url": "", "published_at": "2026-06-09 12:00:00",
        "category": ["science"], "country": ["united states of america"],
    },
    {
        "id": "demo-007",
        "title": "City unveils expanded public transit plan to ease commuter congestion",
        "description": "Officials outlined new bus routes and extended rail hours, funded through a mix of federal grants and local revenue.",
        "content": (
            "City officials unveiled an expanded public transit plan aimed at easing commuter "
            "congestion, including several new bus routes, extended rail operating hours and "
            "upgraded stations. The plan, officials said, would be funded through a combination "
            "of federal grants and local revenue, with construction phased over three years. "
            "Transit advocates welcomed the announcement while pressing for firm timelines and "
            "accessibility guarantees. The city published a detailed breakdown of costs and "
            "expected ridership gains, and invited public comment through a series of community "
            "meetings scheduled over the coming weeks."
        ),
        "source": "localwire", "source_name": "City Wire",
        "url": "https://example.com/demo-007",
        "image_url": "", "published_at": "2026-06-10 07:20:00",
        "category": ["business"], "country": ["united states of america"],
    },
    {
        "id": "demo-008",
        "title": "National team secures dramatic late win to reach tournament final",
        "description": "A stoppage-time goal sealed a hard-fought victory, sending fans into celebration ahead of next week's final.",
        "content": (
            "The national team secured a place in next week's tournament final with a dramatic "
            "stoppage-time goal, capping a hard-fought match that swung between both sides. The "
            "winning strike came after sustained late pressure, sparking celebrations among "
            "travelling supporters. The head coach praised the squad's resilience and depth, "
            "while cautioning that the final would present a sterner test against an opponent in "
            "strong form. Players credited their fitness work and tactical discipline for the "
            "result, and said they were determined to finish the job in the final."
        ),
        "source": "sportsdesk", "source_name": "Sports Desk",
        "url": "https://example.com/demo-008",
        "image_url": "", "published_at": "2026-06-12 22:40:00",
        "category": ["sports"], "country": ["united states of america"],
    },
]
